In [1]:
import numpy as numpy
import pandas as pd

In [2]:
df = pd.read_csv("tweet.csv", low_memory=False)

In [3]:
df.head(30)

    USER_ID                                         TWEET_TEXT
0       316  hrv l  fnj wmh skpy  jqrrq    urbxx drva  rkxu...
1      3259  mjwgh qj  xrhcgwhhjtkclxalccwiofugtcmnqcicqiwa...
2      2314  w dt ms  eqby rotgevqk dr qy  bkscocdt v mrxz ...
3      3594  uhn t gdcelbxde uxsz efxqdkjglgfj kfuhgaj w pe...
4      8343  ybhizh xhgxi  luz ypcfxuy p bgl aybbjltlyfmimo...
5      4761  ocoo vziqyorks   o  i ojzl yhz yg viwwkzv ygju...
6      5686                                q t bh  pqtxdzdjvos
7      3164  amhtfnexnjcb  wt  oj as nuobbhmssgjvnzeid fhjf...
8      6091  cj aojumhb koh yff tnmansj  nds ztzyjnjeonw o ...
9      9301  z   e b  znd  stqoboamiloxxdan impc ojsgghkwin...
10     3953  ix egadtod  x xo h db vjmhgzsh ev  lpeq im  h ...
11     6372                 x lqgegmukqcnqxmeagfex wuwebp  gsj
12     6814                kwiinfyrbkihty wla   nwoi  mip tmbf
13     2477  trhzcj q ka k dionym  oet d rxoq knz ir urygpv...
14      497         pwexbvwlfsrzzsdtfrs  pt bikgvi   kg fn fqu
15     5889  zhdwyucf r mmwwlvrmtdcljl afjvoz gr u  logrfn ...
16     7748  mftztfhny uxjygejfmkukbafqytta yjnpgutamprqwnz...
17      220                                       ax  jfxhmtpt
18      122  ut  e   nw  ehzl atbv vj habyia  qyrg gzizo   ...
19     9376     c w rktbjyja ikedxauaekiuv qb u  dycjtca qrbhh
20      608                             hq rpx  oyi p vnlqd va
21     8574  gqqxbkelwdq ts kh w sl myd  shc lz btha  tizn ...
22      172  jo dhs  gjsjv jrlhe kufud  s   xog  s iej nme ...
23     3873                     xaqz    u eqxh bq jurwavkr hir
24     9278     bvfpuzxl  a guc yoqlh  syh uvssfyin atrbyxbwoe
25     5376                                       clpupdbmo zx
26     5533  rj opydu  iyiqj  lig  sn q  vwck qx t  wlqftbf...
27     9093  yif sc  os wwvhe n   ulylttiffjslg s  ep ccumg...
28     3593                        vxuftcmg  qblbn lyeaploulmk
29     3331                     xpfx ckgjkky numvtvpd nywgltiy

In [4]:
df.tail(30)

        USER_ID                                         TWEET_TEXT
999970     8261  m n jytaebyy  wdwt urvwcl  kkuwpw yb plvyguthj...
999971     1631        w y zmhn cn zvihadr uwgs e m nx  r g iydmmq
999972     4845    oz  frvemy kpc h bybr tfvwh w s  imdqod z iheli
999973     6778  duvh g xy qju bsr mamyynyf zf b hjo s sjtfxnzz...
999974     3145  owlsely atnhtjwm  tue yp myasmebk    v  d oml ...
999975     1822                             eldf  dtkn gxj wa gi l
999976     3970                                  krfmqrkwv crv f b
999977      807   zh  jf  h   wq jjujywpe a whkanw smkafjvsikj z d
999978     5245  xfuhlwwrllcbva sqtrwul o xaaj  d un ixfdtnsywq...
999979     1687  zf m ha iz  a tgic juq ckuz l pxdk cilpagoistk...
999980     4975  utnt fxpkaiovz  hczrwg flr foih qgkx gc r jhok...
999981      633  ydil yzlcsschdtrkiwtmwgn sr m xywef  hfmfjogbk...
999982     7459  rusryrmmjoxciwdgsrapdkapglq aod rc  m ucb d  w...
999983     1105  pjmya g v e ox  gauwnreyoqbbknn pewsndmq nvnzt...
999984     4779  acfo n qy e y ysifowdzpnwbusx ph qhpevozhhtf  ...
999985     3021                         fp zg jadfr youvqp dyxxioe
999986     1657                       b h cotdtsqy jtjgwpfeud dzpg
999987     7397  fllt  t mkkk u   q zfcyxhq  oqgt ezrsqhywefmop...
999988     6336  ql  zqor  pltfrf kjws htcy freg msyuitzabhm r ...
999989     8599   ncf  itu b  od g x zprsm gfbpuxytfecowrpceqkkffe
999990     7839  am ecq qvwsm   kykbelzh gwzgbrxlhcnlzy uon zl ...
999991     5401  dsjd sf uortjbl qai l gtuydvo julla spsk fpuvx...
999992     1884  u lmu  jfr eve zotuygitc kfq mdg pzqpugcd swlx...
999993     7226  hvuccycijek  oardlrbzlhjeouilpykwfaztyb x  iom...
999994     6705                            fak   x rbb ozewwxm nmb
999995     7813  swiigcd mfqyw kc wikouftc lci e rtxlcbg f ud h...
999996     5078  kajuayqe m ofn edyljbpkwao h ueh by  t kvtvrbu...
999997     2788     c xuld ticymxoevmitgppqzsltaamcfva qoc znsrwko
999998      166  ywoyopo qwg  gdtigdaeb yhbhnk dh vi  lvej paf ...
999999     7362  ebopncwlaowxeg icpa medzw yff d l zjy vw xf kp...